from commonprefix import commonprefix
from fizzbuzz import fizzbuzz
from inttoromain import inttormain
from lenoflastword import lenoflastword
from majority import majority
from PalindromeNumber import PalindromeNumber
from plusone import plusone
from poweroftwo import poweroftwo
from romantoint import romantoint
from singlenumber import singlenumber
from smallerthancurrent import smallerthancurrent
from thirdmaximum import thirdmaximum
from TwoSum import TwoSum
from valid-parentheses import valid-parentheses